FROM docker.io/library/ubuntu:24.04

RUN apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
      python3 libwayland-client0 ca-certificates tar gzip >/dev/null && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
